CREATE TABLE IF NOT EXISTS club_members(id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, club_id INTEGER, name TEXT, born INTEGER, FOREIGN KEY (club_id) REFERENCES club(id));
CREATE TABLE IF NOT EXISTS club_sansays(id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, club_id INTEGER, name TEXT, FOREIGN KEY (club_id) REFERENCES club(id));
