DROP TABLE IF EXISTS club_members;
DROP TABLE IF EXISTS club_sansays;
CREATE TABLE IF NOT EXISTS members(id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, club_id INTEGER, name TEXT, born INTEGER, FOREIGN KEY (club_id) REFERENCES club(id));
CREATE TABLE IF NOT EXISTS sensei(id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, club_id INTEGER, name TEXT, FOREIGN KEY (club_id) REFERENCES club(id));
